APP_NAME = "Maailmasampo"

WINDOW_WIDTH_SCALE = 0.6
WINDOW_HEIGHT_SCALE = 0.6
WINDOW_MIN_WIDTH_SCALE = 0.12
WINDOW_MIN_HEIGHT_SCALE = 0.22

DEFAULT_FONT = "TkDefaultFont"
DEFAULT_FONT_SIZE = 12

SCALE_FONT_UP_EVENT_TRIGGER = "<Control-Up>"
SCALE_FONT_DOWN_EVENT_TRIGGER = "<Control-Down>"
SCALE_FONT_INCREMENT_SIZE = 2
SCALE_FONT_MAX_SIZE = 36
SCALE_FONT_MIN_SIZE = 8

LOGOUT_MESSAGE = "Kirjauduit ulos."

RESULT_LIST_NUMBER_OF_COLUMNS = 3
RESULT_LIST_COLUMN_NAMES = ["Nimi", "Luokka", "Haltija"]
